# Generated by Django 5.2 on 2025-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_marca_alter_car_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
